"""Adicionando email ao Usuario

Revision ID: e973e1684c97
Revises: 343246ee01cd
Create Date: 2023-06-03 13:18:44.049821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e973e1684c97'
down_revision = '343246ee01cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps_v1_usuario', sa.Column('email', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'apps_v1_usuario', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apps_v1_usuario', type_='unique')
    op.drop_column('apps_v1_usuario', 'email')
    # ### end Alembic commands ###
